### PR TITLE
Updated code sample in README

### PR DESCRIPTION
**Pull request by sethlivingston**
- http://stackoverflow.com/questions/26614738/issue-running-karma-task-from-gulp
- Workaround for https://github.com/gulpjs/gulp/issues/587

### CODE REVIEW

**Comment by pkozlowski-opensource** [comment]
@sethlivingston I'm afraid that this change is not good for several reasons:
* it doesn't propagate Karma exit code to gulp 
* it updates only README without updating the actual build example

But most of all, I'm not sure what the exact problem is and the SO question / answers are pretty vague. Could you please clearly state what is your exact problem and how this PR helps with it?

**Comment by sethlivingston** [comment]
I see your point.

The problem is that if you're using this code in the context of `gulp.watch`, then it will shut down the watch and exit to the console. Unlike when you're running a build on a CI server, eating the exit code and just viewing the errors on the console is sufficient when you're running `gulp.watch` in your local development environment.

**Comment by pkozlowski-opensource** [comment]
The problem is that you are using `gulp.watch` instead of using Karma's built-in watch capabilities, see: https://github.com/karma-runner/gulp-karma/blob/f8c0baeaf478f03ae6979b65dea31a468de82a20/gulpfile.js#L17-L21

**Comment by sethlivingston** [comment]
The root problem is not with Karma, it's with Gulp and will be addressed in v4. Let's ditch this PR. See https://github.com/gulpjs/gulp/issues/71.

**Comment by sethlivingston** [comment]
Thanks!

**Comment by pkozlowski-opensource** [comment]
Right, if you want to catch errors in `gulp.watch` then you need some plumbers etc. But then again, for now I would advice using build-in Karma watching.

**Pull request closed without merging**
